In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


---
**Task 1.** У тебе є дані по користувачу за два дні:

- **День 1**: вектор `v1 = (перегляди, лайки, коментарі) = (10, 3, 1)`
- **День 2**: `v2 = (7, 5, 0)`

In [5]:
import numpy as np

v1 = np.array([10, 3, 1])
v2 = np.array([7, 5, 0])
print(v1 + v2)
# use operation + in numpy 
# code

[17  8  1]


---
Task 1.1 
Дані
У користувача є активність за 3 дні:

- День 1 → `v1 = (12 переглядів, 3 лайки, 1 коментар)`
- День 2 → `v2 = (20, 5, 0)`
- День 3 → `v3 = (8, 2, 1)`

In [6]:
import numpy as np

v1 = np.array([12, 3, 1])
v2 = np.array([20, 5, 0])
v3 = np.array([8, 2, 1])
print(v1 + v2 + v3)
# use operation + in numpy 
# code

[40 10  2]


---
**Task 2.** Є два користувачі зі схожого сегменту:

> u1 = (перегляди, лайки, підписки) = (30, 4, 1) \
> u2 = (20, 6, 0)

Потрібно зрозуміти, чим відрізняється їхня поведінка.

In [7]:
import numpy as np

u1 = np.array([30, 4, 1])
u2 = np.array([20, 6, 0])
print (u1 - u2)
# use operation - in numpy
# code

[10 -2  1]


---
**Task 2.2**
Поведінка користувача за 2 тижні:

Тиждень 1 → w1 = (100 переглядів, 15 лайків, 3 підписки)

Тиждень 2 → w2 = (140, 18, 5)

In [15]:
import numpy as np

w1 = np.array([100, 15, 3])
w2 = np.array([140, 18, 5])
print (w2 - w1)
# use operation - in numpy

[40  3  2]


---
**Task 3.1**  З’ясувати, хто “сильніший” за загальною активністю.

Два користувачі: \
u1 = (50 переглядів, 10 лайків, 4 підписки) \
u2 = (70, 5, 1)



In [14]:
import numpy as np

u1 = np.array([50, 10, 4])
u2 = np.array([70, 5, 1])
print(np.linalg.norm(u1), np.linalg.norm(u2))
# use linalg.norm

51.146847410177685 70.18546858146635


---
**Task 4.** Двоє користувачів у просторі ознак:

> u1 = (перегляди, лайки) = (10, 2) \
> u2 = (15, 5)

Потрібно:
> знайти відстань між ними (евклідова), \
> зрозуміти, хто “активніший” у загальному масштабі.

In [21]:
# 1. Відстань між користувачами
u1 = np.array([10, 2])
u2 = np.array([15, 5])
# use np.linalg.norm
# code 
print(np.linalg.norm(u1), np.linalg.norm(u2))
print(np.linalg.norm(u1-u2))
print(np.linalg.norm(u1) - np.linalg.norm(u2))
# 2. Рівень активності кожного (довжина вектора)
# use np.linalg.norm
# code 


10.198039027185569 15.811388300841896
5.830951894845301
-5.613349273656327


---
**Task 5.** Нормалізація поведінкових фіч перед кластеризацією


In [ ]:
import numpy as np

users = np.array([
    [10, 3, 1],
    [40, 2, 0],
    [20, 5, 2],
    [15, 1, 1],
    [60, 7, 3]
])

# use linalg.norm(ax)
norm_ = np.linalg.norm(users, axis = 1, keepdims=True)
print(norm_)
# users / by previos step
# np.linalg.norm(users, axis=1, keepdims=True) — це обчислення норм (довжин) векторів уздовж рядків матриці users.
# np.linalg.norm() — функція для обчислення норми (за замовчуванням — евклідової, L2).
# axis=1 означає: обчислюємо норму для кожного рядка окремо.
# keepdims=True зберігає вимірність результату, тобто замість форми (n,) ви отримаєте (n, 1).
# Це корисно, коли пізніше потрібно буде виконувати поелементне ділення users / norms.

normalize_users = users / norm_
print(normalize_users)

# use linalg.norm
# users / by previos step

[[10.48808848]
 [40.04996879]
 [20.71231518]
 [15.06651917]
 [60.4814021 ]]
[[0.95346259 0.28603878 0.09534626]
 [0.99875234 0.04993762 0.        ]
 [0.9656091  0.24140227 0.09656091]
 [0.99558497 0.06637233 0.06637233]
 [0.99204049 0.11573806 0.04960202]]


---
**Task 5.** Оцініть наскільки користувачу підходить товар

In [ ]:
# user data 
#u = (0.2, 0.8, 0.3, 0.1)

# product data
#p = (0.25, 0.75, 0.2, 0.15)


import numpy as np

u = np.array([0.2, 0.8, 0.3, 0.1])
m = np.array([0.25, 0.75, 0.2, 0.15])

score = np.dot (u, m) 
print(score)



0.7250000000000002


In [ ]:
# cosins sim
import numpy as np

def cos_sim(a, b):
    return np.dot(a,b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(f"cos(u, p) =", cos_sim(u, p))


cos(u, p) = 0.9981379987582255
