### Matrix and operation. Date: 2025-12-12

**Topics**:
> 1. Matrix definition
> 2. Matrix operation

**Materials**:
> 1. [Python Matrix](https://www.geeksforgeeks.org/python/python-matrix/)
> 2. [Matrix operation](https://www.geeksforgeeks.org/maths/matrix-operations/)

#### Визначення:
**Матриця** — це прямокутна таблиця чисел, впорядкована у m рядках та n стовпцях.

**Позначення:**
        𝐴 ∈ 𝑅𝑚×𝑛, 𝑎𝑖𝑗—елемент у рядку 𝑖 та стовпці 𝑗

![](https://i.sstatic.net/r2Sko.gif)


Будь-яка таблиця даних (users × features, items × ratings, дата × канали) — це матриця.
	​

Рядки — користувачі, стовпці — ознаки.

#### **Cтруктура матриці**
Матриця складається з: \
    - **елементів** \
    - **рядків** \
    - **стовпців** \
    - **розмірності (shape)**

Приклад:
A = [[1, 2, 3],
     [4, 5, 6]]

#### **Властивості**
Розмір (shape)

Матриця має розмір m × n, де:
- m — число рядків
- n — число стовпців


#### Види матриць 

##### Нульова матриця
**Визначення:** Матриця, усі елементи якої дорівнюють нулю.

![](https://images.deepai.org/glossary-terms/b289323026484ce4829196086d3cd639/zero_matrix.png)

**Приклади використання:**
> Початкові параметри моделі = 0 (наприклад, ініціалізація градієнтів).
> Результат віднімання однакових векторів у кластеризації: 𝑥−𝑥=0, x−x=0

**Властивості:**
> 𝐴+0=𝐴, A+0=A \
> 0⋅𝐴=0 \
> адитивний нейтральний елемент \
> не змінює структуру розмірності матриць

---
#### Одинична матриця
**Визначення:** Квадратна матриця з одиницями на діагоналі.

![](https://purecalculators.com/img/MatrixTranspose13.png)

**Властивості:**
> 𝐼𝐴=𝐴, IA=A \
> 𝐼𝑥=𝑥 Ix=x

--- 
#### Діагональна матриця

**Визначення:** Матриця, де всі позадіагональні елементи = 0.

![](https://hadrienj.github.io/assets/images/2.6/diagonal-and-symmetric-matrices.png)

**Приклади використання:**
> у алгоритмах МЛ \
> нормалізації ознак

**Властивості:**
> підсилює або послаблює кожну вісь окремо \
> математичні перетворення 

---
#### Верхня та нижня трикутні матриці

![Верхня трикутна]()


![Нижня трикутна](https://lh6.googleusercontent.com/proxy/2RY9CDNrRLxtMAUk7TciOg3VdvDmNI_Bx0cIqOMHjyy2uMVAlqo_yyIcjmasDCQrmKE_)

**Приклади:**
> використовується у розв’язанні систем рівнянь при регресії. \
> чисельні методи оптимізації, де кожен крок включає вирішення трикутної системи.

**Властивості:**
> інвертуються значно швидше, ніж загальні матриці
> в алгоритмах робить швидше перетворення O(n^3) -> O(n^2)

---
#### Симетрична матриця

**Визначення:** 𝐴=𝐴𝑇, A=AT


**Приклади:**
> Матриця кореляцій \
> Матриця відстаней у кластеризації 

---
#### Sparse матриця

**Визначення:** Матриця, у якій більшість елементів = 0.

![](https://media.geeksforgeeks.org/wp-content/uploads/Sparse-Matrix-Array-Representation1.png)

**Приклади:**
> рекомендаційні системи (user x item) \
> матриці суміжності графів

In [1]:
arr = [
    [1, 2, 3]
    , [4, [5, 11, 12], 6]
    , [7, 8, 9]
]
print(arr[1][1][1])

11


In [25]:
arr = [i for i in range(1, 15)]

dp = [0] * len(arr)

dp[0] = arr[0]

for i in range(1, len(arr)):
    dp[i] = dp[i - 1] + arr[i]

print(arr) 
print(dp)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105]


In [27]:
# Zeroes matrix
import numpy as np

A = np.zeros((3, 4))
print(A)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [46]:
# Ones matrix
I = np.eye(4)
print(I)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
# Diag matrix
D = np.diag([3, 7, -2])
print(D)


[[ 3  0  0]
 [ 0  7  0]
 [ 0  0 -2]]


In [30]:
# Upper triangle matrix
U = np.triu([[2, 5, 3],
             [4, 4, 1],
             [8, 2, 7]])
print(U)


[[2 5 3]
 [0 4 1]
 [0 0 7]]


In [32]:
# Symmetric matrix
A = np.array([[4, 2, 7],
              [2, 5, 1],
              [7, 1, 3]])

print(A)
print(np.allclose(A, A.T))


[[4 2 7]
 [2 5 1]
 [7 1 3]]
True


In [31]:
from scipy.sparse import csr_matrix

R = csr_matrix([[5, 3, 0, 0],
                [4, 0, 0, 2],
                [1, 1, 0, 5],
                [0, 0, 5, 4]])

print(R)
print("Формат:", type(R))


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	5
  (0, 1)	3
  (1, 0)	4
  (1, 3)	2
  (2, 0)	1
  (2, 1)	1
  (2, 3)	5
  (3, 2)	5
  (3, 3)	4
Формат: <class 'scipy.sparse._csr.csr_matrix'>



####  Транспонування матриці

**Визначення:** Транспонування — це операція, що міняє рядки та стовпці місцями.
[A^T_{ij} = A_{ji}]

* Рядки стають стовпцями.
* Вектор-рядок -> вектор-стовпець, і навпаки.



### **Де застосовується**

* у формулі регресії 
* у множенні матриць, де розмірності мають відповідати
* роботи з ознаками у ML зручно переходити між `samples × features` та `features × samples`

---

####  Додавання матриць

**Визначення:** Дві матриці можна додавати, якщо вони **однакового розміру**.
  [(A + B)*{ij} = A*{ij} + B_{ij}]

Елемент додається до відповідного елемента.

**Приклади:**

* агрегації у нейромережах
* оновлення ваг у оптимізаторах (Adam, SGD)
* операції між різними таблицями ознак

---

#### Множення матриць (матричний добуток)

**Визначення:**  Множити можна тоді, коли кількість стовпців першої матриці = кількості рядків другої.

Беремо рядок з A і стовпець з B, множимо поелементно і складаємо.

Розмір = (кількість рядків першої) × (кількість стовпців другої). Приклад: (2×3) · (3×2) = (2×2). A.shape[1] == B.shape[0]

* Добуток рядка A на стовпець B -> скаляр.
* Матричне множення = лінійна комбінація стовпців.
* Завжди перевіряй розмірності: `A.shape[1] == B.shape[0]`.
* Використовуй оператор `@`, а не `dot`, він більш читабельний.

**Приклади використання:**
* прогноз у лінійній моделі
* LLM / трансформери


---

#### Поелементне множення 

Виконується поелементно.


**Приклади:**

* фільтрація ознак:`X * mask`
* нормалізація
* нейронні мережі (attention masking)
* швидкий спосіб помножити матрицю на ваги такого ж розміру.

---

####  Множення матриці на скаляр


**Приклади:**
* масштабування ознак
* зміна ваг у регуляризації
* модифікація векторів у gradient descent

---

#### Обчислення рангу матриці

Ранг = кількість **лінійно незалежних** рядків/стовпців.

* Якщо `rank < n_features` → мультиколінеарність.
* Для регресії завжди перевіряй ранг матриці ознак X.

**Приклади:**
* детект проблеми мультиколінеарності
* визначення розмірності простору
* у PCA ранг визначає максимум компонент

---

#### Обернена матриця

**Визначення:** [A^{-1}A = I]. Обернена матриця існує тільки якщо `det(A) ≠ 0`.


---

#### Determinant
**Визначення:** `det(A)` = масштабування об'єму при лінійному перетворенні.

> det = 0 -> ознаки дублюють одна одну \
> det ≈ 0 -> модель нестабільна \
> det > 0 -> можна обчислювати коефіцієнти

* маленький або майже нульовий det → матриця «погана»,  вироджена.


---

####  Норма матриці та вектора

**L2-norma:**
![](https://i.sstatic.net/XlCRF.png)

**Фробеніусова норма:** Фробеніусова норма = сума квадратів
![](https://ic.pics.livejournal.com/yu_xuan/12681078/216868/216868_600.png)

**Приклади:**

* регуляризації (L1/L2)
* оцінки величини ваг моделі
* оцінки схожості embedding-векторів


---

* `@` → матричний добуток
* `*` → поелементне множення
* `A.T` → транспонування
* `matrix_rank()` → перевірка мультиколінеарності
* `norm()` → оцінка величини / довжини

---



In [33]:
# транспонування
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A)
A_T = A.T
print(A_T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np
a = [
    [1, 2]
    , [3, 4]
]

b = [
    [10, 20]
    , [30, 40]
]
# price = 0.5, rewies = 0.4,  -> 1, 

In [5]:
import numpy as np
# додавання 
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 20],
              [30, 40]])

C = A + B
print(C)

[[11 22]
 [33 44]]


In [6]:
import numpy as np
# множення
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

C = A @ B   # або np.dot(A, B)
print(C)
# [
#   5*0.3 + 10*0.7 = 8.5
#   2*0.3 +  4*0.7 = 3.4
# ]

[[19 22]
 [43 50]]


In [ ]:
X = [
  [5, 10],
  [2,  4]
]


W = [
  [0.3],
  [0.7]
]


# X @ W =
# [
#   5*0.3 + 10*0.7 = 8.5
#   2*0.3 +  4*0.7 = 3.4
# ]


In [42]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 20],
              [30, 40]])

C = A * B
print(C)

[[ 10  40]
 [ 90 160]]


In [39]:
A = np.array([[1, 2],
              [3, 4]])

C = 5 * A
print(C)

[[ 5 10]
 [15 20]]


In [40]:
# rank 
A = np.array([[1, 2, 3],
              [2, 4, 6],
              [3, 6, 9]])

rank = np.linalg.matrix_rank(A)
print("Ранг:", rank)

Ранг: 1


In [7]:
A = np.array([[4, 2],
              [3, 1]])

A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.5  1. ]
 [ 1.5 -2. ]]


In [8]:
# det
A = np.array([[4, 2],
              [3, 1]])

det = np.linalg.det(A)
print(det)

-2.0


In [9]:
x = np.array([3, 4])
print(np.linalg.norm(x))

5.0


In [45]:
A = np.array([[1, 2],
              [3, 4]])

print(np.linalg.norm(A, 'fro'))


5.477225575051661


In [7]:
# !!!! Need install seaborn, numpy, panda !!!!
import seaborn as sns
import numpy as np
import pandas as pd

df = sns.load_dataset("titanic").dropna(subset=["age", "fare", "pclass", "survived"])
df = df[["age", "fare", "pclass", "survived"]]
df.head()


age     fare  pclass  survived
0  22.0   7.2500       3         0
1  38.0  71.2833       1         1
2  26.0   7.9250       3         1
3  35.0  53.1000       1         1
4  35.0   8.0500       3         0

In [34]:
df_test = sns.load_dataset("titanic")

In [36]:
df_test.shape

(891, 15)

In [35]:
df_test.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [8]:
X = df[["age", "fare", "pclass"]].values  
y = df["survived"].values                 

In [ ]:
# корреляція
XtX = X.T @ X
XtX


array([[ 780231.4745   ,  788357.425814 ,   44223.84     ],
       [ 788357.425814 , 2856142.9817713,   37879.3612   ],
       [  44223.84     ,   37879.3612   ,    4073.       ]])

In [41]:
# ранг матриці: мультиколінеарності
np.linalg.matrix_rank(X) # Якщо ранг < кількості ознак -> потенційно проблема

np.int64(3)

In [ ]:
# детермінанта
det = np.linalg.det(XtX)
det
# Якщо det ≈ 0 -> ознаки сильно залежні -> модель буде нестабільною
# Якщо det велике -> прогноз стабільний


np.float64(2480946563493686.5)

In [37]:
df.head(1)

age  fare  pclass  survived
0  22.0  7.25       3         0

In [12]:
beta = np.linalg.inv(XtX) @ X.T @ y
beta


array([0.00337173, 0.0034799 , 0.06434391])

In [14]:
X_norm = X / X.max(axis=0)
X_norm[:5]

array([[0.275     , 0.01415106, 1.        ],
       [0.475     , 0.13913574, 0.33333333],
       [0.325     , 0.01546857, 1.        ],
       [0.4375    , 0.1036443 , 0.33333333],
       [0.4375    , 0.01571255, 1.        ]])

In [13]:
X_scaled = 0.01 * X

In [17]:
X_scaled

array([[-0.53037664, -0.51897787,  0.91123237],
       [ 0.57183099,  0.69189675, -1.47636364],
       [-0.25482473, -0.50621356,  0.91123237],
       ...,
       [-0.73704057, -0.08877362, -1.47636364],
       [-0.25482473, -0.08877362, -1.47636364],
       [ 0.15850313, -0.50952283,  0.91123237]], shape=(714, 3))

In [15]:
# !!!! потрібно встановити Sklearn !!!!
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
model_raw = LinearRegression()
model_raw.fit(X, y)

y_pred_raw = model_raw.predict(X)

print(model_raw.coef_)
print("MSE :", mean_squared_error(y, y_pred_raw))


[-0.00796079  0.00058081 -0.24147906]
MSE : 0.19703791065590445


In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model_scaled = LinearRegression()
model_scaled.fit(X_scaled, y)

y_pred_scaled = model_scaled.predict(X_scaled)

print(model_scaled.coef_)
print("MSE:", mean_squared_error(y, y_pred_scaled))


[-0.1155614   0.0307143  -0.20227799]
MSE: 0.19703791065590445
